// export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_NAME = 'SET_NAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_ADDR = 'SET_ADDR'
export const SET_ID='SET_ID'